
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jul 26 18:20:58 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 23;
  public static final int MAP = 7;
  public static final int LBRACKET = 42;
  public static final int CONST = 8;
  public static final int GE = 30;
  public static final int LPAREN = 40;
  public static final int SEMI = 36;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 5;
  public static final int MINUS = 21;
  public static final int NUMBERCONST = 46;
  public static final int RPAREN = 41;
  public static final int AND = 33;
  public static final int LT = 31;
  public static final int OR = 34;
  public static final int COMMA = 38;
  public static final int CLASS = 3;
  public static final int INC = 25;
  public static final int PLUS = 20;
  public static final int MULTIPLY = 22;
  public static final int ASSIGN = 35;
  public static final int IF = 16;
  public static final int DOT = 39;
  public static final int LE = 32;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 43;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MOD = 24;
  public static final int IDENT = 49;
  public static final int BREAK = 19;
  public static final int VOID = 12;
  public static final int EQ = 27;
  public static final int COLON = 37;
  public static final int UNION = 6;
  public static final int LBRACE = 44;
  public static final int ELSE = 17;
  public static final int READ = 10;
  public static final int CHARCONST = 48;
  public static final int WHILE = 15;
  public static final int RBRACE = 45;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 4;
  public static final int PROG = 2;
  public static final int NE = 28;
  public static final int DEC = 26;
  public static final int GT = 29;
  public static final int PRINT = 9;
  public static final int DO = 14;
}

